title: InTraC Knowledge Base
description: >-
  The central hub for finding, analysing and disseminating data of the
  InTraC Collaborative Research Centre — Immunothrombosis and
  Thromboinflammation Collaborative.
url: ""
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CONTRIBUTING.md
  - node_modules
  - vendor

defaults:
  - scope:
      path: ""
    values:
      layout: page
